language: c
matrix:
  include:

    - os: windows
      language: sh
      filter_secrets: false

script:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "windows" ]]; then
      choco install make
      cp "C:\\ProgramData\\chocolatey\\bin\\gcc.exe" "C:\\ProgramData\\chocolatey\\bin\\cc.exe"
    fi
  - ./configure -thread -fast
  - make clean
  - make depend
  - make -j4
  - make run
